version: '3.9'

services:

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
      - "7473:7473"
    environment:
      - NEO4J_AUTH=neo4j/brahmsian
      - NEO4J_PLUGINS=["apoc"]
